spring.cloud.config.allow-override: true
spring.cloud.config.override-none: true
spring.cloud.config.override-system-properties: false

server:
  port: 5001
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
eureka:
  client:
    service-url:
      defaultZone: http://panda-server:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: "jdbc:mysql://${zipkin_mysql_host:172.31.18.86}:3306/cloud?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true"
    driver-class-name: com.mysql.jdbc.Driver
    username: "${zipkin_mysql_user:root}"
    password: "${zipkin_mysql_passwd:root}"
    dbcp2:
      max-idle: 10
      min-idle: 5
      test-on-borrow: false
      time-between-eviction-runs-millis: 18800
      test-while-idle: true
      validation-query: SELECT 1
    hikari:
      minimum-idle: 0

  rabbitmq:
    host: 172.31.18.86
    port: 5672
    username: admin
    password: admin
    virtual-host: vhost

  zipkin:
    enabled: true

  sleuth:
    sampler:
      probability: 1.0
    enabled: false



